// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_request_filter(input: &crate::types::RequestFilter, writer: ::aws_smithy_xml::encode::ElWriter) -> Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    if let Some(var_1) = &input.request_and {
        let inner_writer = scope.start_el("And");
        crate::protocol_serde::shape_request_and::ser_request_and(var_1, inner_writer)?
    }
    scope.finish();
    Ok(())
}

