// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_request_object(input: &crate::types::RequestObject, writer: ::aws_smithy_xml::encode::ElWriter) -> Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    #[allow(unused_mut)]
    let mut scope = writer.finish();
     {
        let mut inner_writer = scope.start_el("Key").finish();
        inner_writer.data(
            input.key.as_str()
        );
    }
    if let Some(var_1) = &input.quiet {
        let mut inner_writer = scope.start_el("Quiet").finish();
        inner_writer.data(
            ::aws_smithy_types::primitive::Encoder::from(*var_1).encode()
        );
    }
    if let Some(var_2) = &input.version_id {
        let mut inner_writer = scope.start_el("VersionId").finish();
        inner_writer.data(
            var_2.as_str()
        );
    }
    scope.finish();
    Ok(())
}

