// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(clippy::unnecessary_wraps)]
pub fn de_get_object_tagging_http_error(_response_status: u16, _response_headers: &::aws_smithy_runtime_api::http::Headers, _response_body: &[u8]) -> std::result::Result<crate::operation::get_object_tagging::GetObjectTaggingOutput, crate::operation::get_object_tagging::GetObjectTaggingError> {
    #[allow(unused_mut)]
    let mut generic_builder = crate::protocol_serde::parse_http_error_metadata(_response_status, _response_headers, _response_body).map_err(crate::operation::get_object_tagging::GetObjectTaggingError::unhandled)?;
    let generic = generic_builder.build();
    Err(crate::operation::get_object_tagging::GetObjectTaggingError::generic(generic))
}

#[allow(clippy::unnecessary_wraps)]
pub fn de_get_object_tagging_http_response(_response_status: u16, _response_headers: &::aws_smithy_runtime_api::http::Headers, _response_body: &[u8]) -> std::result::Result<crate::operation::get_object_tagging::GetObjectTaggingOutput, crate::operation::get_object_tagging::GetObjectTaggingError> {
    Ok({
        #[allow(unused_mut)]
        let mut output = crate::operation::get_object_tagging::builders::GetObjectTaggingOutputBuilder::default();
        output = crate::protocol_serde::shape_get_object_tagging::de_get_object_tagging(_response_body, output).map_err(crate::operation::get_object_tagging::GetObjectTaggingError::unhandled)?;
        output = output.set_content_type(
            crate::protocol_serde::shape_get_object_tagging_output::de_content_type_header(_response_headers)
                                    .map_err(|_|crate::operation::get_object_tagging::GetObjectTaggingError::unhandled("Failed to parse ContentType from header `Content-Type"))?
        );
        output = output.set_x_amz_version_id(
            crate::protocol_serde::shape_get_object_tagging_output::de_x_amz_version_id_header(_response_headers)
                                    .map_err(|_|crate::operation::get_object_tagging::GetObjectTaggingError::unhandled("Failed to parse XAmzVersionId from header `x-amz-version-id"))?
        );
        output.build()
    })
}

#[allow(unused_mut)]
pub fn de_get_object_tagging(inp: &[u8], mut builder: crate::operation::get_object_tagging::builders::GetObjectTaggingOutputBuilder) -> Result<crate::operation::get_object_tagging::builders::GetObjectTaggingOutputBuilder, ::aws_smithy_xml::decode::XmlDecodeError> {
    let mut doc = ::aws_smithy_xml::decode::Document::try_from(inp)?;
    
                        #[allow(unused_mut)]
                        let mut decoder = doc.root_element()?;
                        #[allow(unused_variables)]
                        let start_el = decoder.start_el();
    if !start_el.matches("GetObjectTaggingResult") {
                            return Err(
                                ::aws_smithy_xml::decode::XmlDecodeError::custom(
                                    format!("encountered invalid XML root: expected GetObjectTaggingResult but got {:?}. This is likely a bug in the SDK.", start_el)
                                )
                            )
                        }
    while let Some(mut tag) = decoder.next_tag() {
        match tag.start_el() {
            s if s.matches("TagSet") /* TagSet com.nifcloud.api.storage.synthetic#GetObjectTaggingOutput$TagSet */ =>  {
                let var_1 =
                    Some(
                        crate::protocol_serde::shape_tag_set::de_tag_set(&mut tag)
                        ?
                    )
                ;
                builder = builder.set_tag_set(var_1);
            }
            ,
            _ => {}
        }
    }
    Ok(builder)
}

