// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_request_lifecycle_configuration(input: &crate::types::RequestLifecycleConfiguration, writer: ::aws_smithy_xml::encode::ElWriter) -> Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    #[allow(unused_mut)]
    let mut scope = writer.finish();
     {
        for list_item_1 in &input.list_of_request_rule {
             {
                let inner_writer = scope.start_el("Rule");
                crate::protocol_serde::shape_request_rule::ser_request_rule(list_item_1, inner_writer)?
            }
        }
    }
    scope.finish();
    Ok(())
}

