// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(clippy::needless_question_mark)]
pub fn de_cors_rule(decoder: &mut ::aws_smithy_xml::decode::ScopedDecoder) -> Result<crate::types::CorsRule, ::aws_smithy_xml::decode::XmlDecodeError> {
    #[allow(unused_mut)]
    let mut builder = crate::types::CorsRule::builder();
    while let Some(mut tag) = decoder.next_tag() {
        match tag.start_el() {
            s if s.matches("AllowedHeader") /* AllowedHeader com.nifcloud.api.storage#CORSRule$AllowedHeader */ =>  {
                let var_1 =
                    Some(
                        Result::<::std::string::String, ::aws_smithy_xml::decode::XmlDecodeError>::Ok(
                            ::aws_smithy_xml::decode::try_data(&mut tag)?.as_ref()
                            .into()
                        )
                        ?
                    )
                ;
                builder = builder.set_allowed_header(var_1);
            }
            ,
            s if s.matches("AllowedMethod") /* AllowedMethod com.nifcloud.api.storage#CORSRule$AllowedMethod */ =>  {
                let var_2 =
                    Some(
                        crate::protocol_serde::shape_list_of_allowed_method::de_list_of_allowed_method(&mut tag)
                        ?
                    )
                ;
                builder = builder.set_allowed_method(var_2);
            }
            ,
            s if s.matches("AllowedOrigin") /* AllowedOrigin com.nifcloud.api.storage#CORSRule$AllowedOrigin */ =>  {
                let var_3 =
                    Some(
                        Result::<::std::string::String, ::aws_smithy_xml::decode::XmlDecodeError>::Ok(
                            ::aws_smithy_xml::decode::try_data(&mut tag)?.as_ref()
                            .into()
                        )
                        ?
                    )
                ;
                builder = builder.set_allowed_origin(var_3);
            }
            ,
            s if s.matches("ExposeHeader") /* ExposeHeader com.nifcloud.api.storage#CORSRule$ExposeHeader */ =>  {
                let var_4 =
                    Some(
                        Result::<::std::string::String, ::aws_smithy_xml::decode::XmlDecodeError>::Ok(
                            ::aws_smithy_xml::decode::try_data(&mut tag)?.as_ref()
                            .into()
                        )
                        ?
                    )
                ;
                builder = builder.set_expose_header(var_4);
            }
            ,
            s if s.matches("MaxAgeSeconds") /* MaxAgeSeconds com.nifcloud.api.storage#CORSRule$MaxAgeSeconds */ =>  {
                let var_5 =
                    Some(
                         {
                            <i32 as ::aws_smithy_types::primitive::Parse>::parse_smithy_primitive(
                                ::aws_smithy_xml::decode::try_data(&mut tag)?.as_ref()
                            )
                            .map_err(|_|::aws_smithy_xml::decode::XmlDecodeError::custom("expected (integer: `smithy.api#Integer`)"))
                        }
                        ?
                    )
                ;
                builder = builder.set_max_age_seconds(var_5);
            }
            ,
            _ => {}
        }
    }
    Ok(builder.build())
}

