// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(clippy::needless_question_mark)]
pub fn de_and(decoder: &mut ::aws_smithy_xml::decode::ScopedDecoder) -> Result<crate::types::And, ::aws_smithy_xml::decode::XmlDecodeError> {
    #[allow(unused_mut)]
    let mut builder = crate::types::And::builder();
    while let Some(mut tag) = decoder.next_tag() {
        match tag.start_el() {
            s if s.matches("Tag") /* Tag com.nifcloud.api.storage#And$Tag */ =>  {
                let var_1 =
                    Some(
                        crate::protocol_serde::shape_tag::de_tag(&mut tag)
                        ?
                    )
                ;
                builder = builder.set_tag(var_1);
            }
            ,
            _ => {}
        }
    }
    Ok(builder.build())
}

