// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct DeleteBucketLifecycleOutput  {
}
impl DeleteBucketLifecycleOutput {
    /// Creates a new builder-style object to manufacture [`DeleteBucketLifecycleOutput`](crate::operation::delete_bucket_lifecycle::DeleteBucketLifecycleOutput).
    pub fn builder() -> crate::operation::delete_bucket_lifecycle::builders::DeleteBucketLifecycleOutputBuilder {
        crate::operation::delete_bucket_lifecycle::builders::DeleteBucketLifecycleOutputBuilder::default()
    }
}

/// A builder for [`DeleteBucketLifecycleOutput`](crate::operation::delete_bucket_lifecycle::DeleteBucketLifecycleOutput).
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
pub struct DeleteBucketLifecycleOutputBuilder {
}
impl DeleteBucketLifecycleOutputBuilder {
    /// Consumes the builder and constructs a [`DeleteBucketLifecycleOutput`](crate::operation::delete_bucket_lifecycle::DeleteBucketLifecycleOutput).
    pub fn build(self) -> crate::operation::delete_bucket_lifecycle::DeleteBucketLifecycleOutput {
        crate::operation::delete_bucket_lifecycle::DeleteBucketLifecycleOutput {
        }
    }
}

