// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct DeleteBucketOutput  {
}
impl DeleteBucketOutput {
    /// Creates a new builder-style object to manufacture [`DeleteBucketOutput`](crate::operation::delete_bucket::DeleteBucketOutput).
    pub fn builder() -> crate::operation::delete_bucket::builders::DeleteBucketOutputBuilder {
        crate::operation::delete_bucket::builders::DeleteBucketOutputBuilder::default()
    }
}

/// A builder for [`DeleteBucketOutput`](crate::operation::delete_bucket::DeleteBucketOutput).
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
pub struct DeleteBucketOutputBuilder {
}
impl DeleteBucketOutputBuilder {
    /// Consumes the builder and constructs a [`DeleteBucketOutput`](crate::operation::delete_bucket::DeleteBucketOutput).
    pub fn build(self) -> crate::operation::delete_bucket::DeleteBucketOutput {
        crate::operation::delete_bucket::DeleteBucketOutput {
        }
    }
}

