// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct PutObjectTaggingOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub x_amz_version_id: ::std::option::Option<::std::string::String>,
}
impl  PutObjectTaggingOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn x_amz_version_id(&self) -> ::std::option::Option<& str> {
        self.x_amz_version_id.as_deref()
    }
}
impl PutObjectTaggingOutput {
    /// Creates a new builder-style object to manufacture [`PutObjectTaggingOutput`](crate::operation::put_object_tagging::PutObjectTaggingOutput).
    pub fn builder() -> crate::operation::put_object_tagging::builders::PutObjectTaggingOutputBuilder {
        crate::operation::put_object_tagging::builders::PutObjectTaggingOutputBuilder::default()
    }
}

/// A builder for [`PutObjectTaggingOutput`](crate::operation::put_object_tagging::PutObjectTaggingOutput).
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
pub struct PutObjectTaggingOutputBuilder {
    pub(crate) x_amz_version_id: ::std::option::Option<::std::string::String>,
}
impl PutObjectTaggingOutputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    pub fn x_amz_version_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.x_amz_version_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_x_amz_version_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.x_amz_version_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_x_amz_version_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.x_amz_version_id
    }
    /// Consumes the builder and constructs a [`PutObjectTaggingOutput`](crate::operation::put_object_tagging::PutObjectTaggingOutput).
    pub fn build(self) -> crate::operation::put_object_tagging::PutObjectTaggingOutput {
        crate::operation::put_object_tagging::PutObjectTaggingOutput {
            x_amz_version_id: self.x_amz_version_id
            ,
        }
    }
}

