// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct RequestObject  {
    #[allow(missing_docs)] // documentation missing in model
    pub key: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub quiet: ::std::option::Option<bool>,
    #[allow(missing_docs)] // documentation missing in model
    pub version_id: ::std::option::Option<::std::string::String>,
}
impl  RequestObject  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn key(&self) -> & str {
        use std::ops::Deref; self.key.deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn quiet(&self) -> ::std::option::Option<bool> {
        self.quiet
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn version_id(&self) -> ::std::option::Option<& str> {
        self.version_id.as_deref()
    }
}
impl RequestObject {
    /// Creates a new builder-style object to manufacture [`RequestObject`](crate::types::RequestObject).
    pub fn builder() -> crate::types::builders::RequestObjectBuilder {
        crate::types::builders::RequestObjectBuilder::default()
    }
}

/// A builder for [`RequestObject`](crate::types::RequestObject).
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
pub struct RequestObjectBuilder {
    pub(crate) key: ::std::option::Option<::std::string::String>,
    pub(crate) quiet: ::std::option::Option<bool>,
    pub(crate) version_id: ::std::option::Option<::std::string::String>,
}
impl RequestObjectBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn key(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.key = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_key(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.key = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_key(&self) -> &::std::option::Option<::std::string::String> {
        &self.key
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn quiet(mut self, input: bool) -> Self {
        self.quiet = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_quiet(mut self, input: ::std::option::Option<bool>) -> Self {
        self.quiet = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_quiet(&self) -> &::std::option::Option<bool> {
        &self.quiet
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn version_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.version_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_version_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.version_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_version_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.version_id
    }
    /// Consumes the builder and constructs a [`RequestObject`](crate::types::RequestObject).
    /// This method will fail if any of the following fields are not set:
    /// - [`key`](crate::types::builders::RequestObjectBuilder::key)
    pub fn build(self) -> ::std::result::Result<crate::types::RequestObject, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::types::RequestObject {
                key: self.key
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("key", "key was not specified but it is required when building RequestObject")
                    )?
                ,
                quiet: self.quiet
                ,
                version_id: self.version_id
                ,
            }
        )
    }
}

