// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct RequestVersioningConfiguration  {
    #[allow(missing_docs)] // documentation missing in model
    pub status: ::std::option::Option<crate::types::StatusOfVersioningConfigurationForPutBucketVersioning>,
}
impl  RequestVersioningConfiguration  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn status(&self) -> ::std::option::Option<& crate::types::StatusOfVersioningConfigurationForPutBucketVersioning> {
        self.status.as_ref()
    }
}
impl RequestVersioningConfiguration {
    /// Creates a new builder-style object to manufacture [`RequestVersioningConfiguration`](crate::types::RequestVersioningConfiguration).
    pub fn builder() -> crate::types::builders::RequestVersioningConfigurationBuilder {
        crate::types::builders::RequestVersioningConfigurationBuilder::default()
    }
}

/// A builder for [`RequestVersioningConfiguration`](crate::types::RequestVersioningConfiguration).
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
pub struct RequestVersioningConfigurationBuilder {
    pub(crate) status: ::std::option::Option<crate::types::StatusOfVersioningConfigurationForPutBucketVersioning>,
}
impl RequestVersioningConfigurationBuilder {
    #[allow(missing_docs)] // documentation missing in model
    pub fn status(mut self, input: crate::types::StatusOfVersioningConfigurationForPutBucketVersioning) -> Self {
        self.status = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_status(mut self, input: ::std::option::Option<crate::types::StatusOfVersioningConfigurationForPutBucketVersioning>) -> Self {
        self.status = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_status(&self) -> &::std::option::Option<crate::types::StatusOfVersioningConfigurationForPutBucketVersioning> {
        &self.status
    }
    /// Consumes the builder and constructs a [`RequestVersioningConfiguration`](crate::types::RequestVersioningConfiguration).
    pub fn build(self) -> crate::types::RequestVersioningConfiguration {
        crate::types::RequestVersioningConfiguration {
            status: self.status
            ,
        }
    }
}

