// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct RequestCorsConfiguration  {
    #[allow(missing_docs)] // documentation missing in model
    pub list_of_request_cors_rule: ::std::vec::Vec::<crate::types::RequestCorsRule>,
}
impl  RequestCorsConfiguration  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn list_of_request_cors_rule(&self) -> & [crate::types::RequestCorsRule] {
        use std::ops::Deref; self.list_of_request_cors_rule.deref()
    }
}
impl RequestCorsConfiguration {
    /// Creates a new builder-style object to manufacture [`RequestCorsConfiguration`](crate::types::RequestCorsConfiguration).
    pub fn builder() -> crate::types::builders::RequestCorsConfigurationBuilder {
        crate::types::builders::RequestCorsConfigurationBuilder::default()
    }
}

/// A builder for [`RequestCorsConfiguration`](crate::types::RequestCorsConfiguration).
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
pub struct RequestCorsConfigurationBuilder {
    pub(crate) list_of_request_cors_rule: ::std::option::Option<::std::vec::Vec::<crate::types::RequestCorsRule>>,
}
impl RequestCorsConfigurationBuilder {
    /// Appends an item to `list_of_request_cors_rule`.
    ///
    /// To override the contents of this collection use [`set_list_of_request_cors_rule`](Self::set_list_of_request_cors_rule).
    ///
    pub fn list_of_request_cors_rule(mut self, input: crate::types::RequestCorsRule) -> Self {
        let mut v = self.list_of_request_cors_rule.unwrap_or_default();
                        v.push(input);
                        self.list_of_request_cors_rule = ::std::option::Option::Some(v);
                        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_list_of_request_cors_rule(mut self, input: ::std::option::Option<::std::vec::Vec::<crate::types::RequestCorsRule>>) -> Self {
        self.list_of_request_cors_rule = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_list_of_request_cors_rule(&self) -> &::std::option::Option<::std::vec::Vec::<crate::types::RequestCorsRule>> {
        &self.list_of_request_cors_rule
    }
    /// Consumes the builder and constructs a [`RequestCorsConfiguration`](crate::types::RequestCorsConfiguration).
    /// This method will fail if any of the following fields are not set:
    /// - [`list_of_request_cors_rule`](crate::types::builders::RequestCorsConfigurationBuilder::list_of_request_cors_rule)
    pub fn build(self) -> ::std::result::Result<crate::types::RequestCorsConfiguration, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::types::RequestCorsConfiguration {
                list_of_request_cors_rule: self.list_of_request_cors_rule
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("list_of_request_cors_rule", "list_of_request_cors_rule was not specified but it is required when building RequestCorsConfiguration")
                    )?
                ,
            }
        )
    }
}

