// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct RequestDelete  {
    #[allow(missing_docs)] // documentation missing in model
    pub list_of_request_object: ::std::vec::Vec::<crate::types::RequestObject>,
}
impl  RequestDelete  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn list_of_request_object(&self) -> & [crate::types::RequestObject] {
        use std::ops::Deref; self.list_of_request_object.deref()
    }
}
impl RequestDelete {
    /// Creates a new builder-style object to manufacture [`RequestDelete`](crate::types::RequestDelete).
    pub fn builder() -> crate::types::builders::RequestDeleteBuilder {
        crate::types::builders::RequestDeleteBuilder::default()
    }
}

/// A builder for [`RequestDelete`](crate::types::RequestDelete).
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
pub struct RequestDeleteBuilder {
    pub(crate) list_of_request_object: ::std::option::Option<::std::vec::Vec::<crate::types::RequestObject>>,
}
impl RequestDeleteBuilder {
    /// Appends an item to `list_of_request_object`.
    ///
    /// To override the contents of this collection use [`set_list_of_request_object`](Self::set_list_of_request_object).
    ///
    pub fn list_of_request_object(mut self, input: crate::types::RequestObject) -> Self {
        let mut v = self.list_of_request_object.unwrap_or_default();
                        v.push(input);
                        self.list_of_request_object = ::std::option::Option::Some(v);
                        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_list_of_request_object(mut self, input: ::std::option::Option<::std::vec::Vec::<crate::types::RequestObject>>) -> Self {
        self.list_of_request_object = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_list_of_request_object(&self) -> &::std::option::Option<::std::vec::Vec::<crate::types::RequestObject>> {
        &self.list_of_request_object
    }
    /// Consumes the builder and constructs a [`RequestDelete`](crate::types::RequestDelete).
    /// This method will fail if any of the following fields are not set:
    /// - [`list_of_request_object`](crate::types::builders::RequestDeleteBuilder::list_of_request_object)
    pub fn build(self) -> ::std::result::Result<crate::types::RequestDelete, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::types::RequestDelete {
                list_of_request_object: self.list_of_request_object
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("list_of_request_object", "list_of_request_object was not specified but it is required when building RequestDelete")
                    )?
                ,
            }
        )
    }
}

