// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct PutBucketPolicyOutput  {
}
impl PutBucketPolicyOutput {
    /// Creates a new builder-style object to manufacture [`PutBucketPolicyOutput`](crate::operation::put_bucket_policy::PutBucketPolicyOutput).
    pub fn builder() -> crate::operation::put_bucket_policy::builders::PutBucketPolicyOutputBuilder {
        crate::operation::put_bucket_policy::builders::PutBucketPolicyOutputBuilder::default()
    }
}

/// A builder for [`PutBucketPolicyOutput`](crate::operation::put_bucket_policy::PutBucketPolicyOutput).
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
pub struct PutBucketPolicyOutputBuilder {
}
impl PutBucketPolicyOutputBuilder {
    /// Consumes the builder and constructs a [`PutBucketPolicyOutput`](crate::operation::put_bucket_policy::PutBucketPolicyOutput).
    pub fn build(self) -> crate::operation::put_bucket_policy::PutBucketPolicyOutput {
        crate::operation::put_bucket_policy::PutBucketPolicyOutput {
        }
    }
}

