// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct DeleteBucketPolicyOutput  {
}
impl DeleteBucketPolicyOutput {
    /// Creates a new builder-style object to manufacture [`DeleteBucketPolicyOutput`](crate::operation::delete_bucket_policy::DeleteBucketPolicyOutput).
    pub fn builder() -> crate::operation::delete_bucket_policy::builders::DeleteBucketPolicyOutputBuilder {
        crate::operation::delete_bucket_policy::builders::DeleteBucketPolicyOutputBuilder::default()
    }
}

/// A builder for [`DeleteBucketPolicyOutput`](crate::operation::delete_bucket_policy::DeleteBucketPolicyOutput).
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
pub struct DeleteBucketPolicyOutputBuilder {
}
impl DeleteBucketPolicyOutputBuilder {
    /// Consumes the builder and constructs a [`DeleteBucketPolicyOutput`](crate::operation::delete_bucket_policy::DeleteBucketPolicyOutput).
    pub fn build(self) -> crate::operation::delete_bucket_policy::DeleteBucketPolicyOutput {
        crate::operation::delete_bucket_policy::DeleteBucketPolicyOutput {
        }
    }
}

