// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`DeleteBucketTagging`](crate::operation::delete_bucket_tagging::builders::DeleteBucketTaggingFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`bucket(impl Into<String>)`](crate::operation::delete_bucket_tagging::builders::DeleteBucketTaggingFluentBuilder::bucket) / [`set_bucket(Option<String>)`](crate::operation::delete_bucket_tagging::builders::DeleteBucketTaggingFluentBuilder::set_bucket):<br>required: **true**<br>(undocumented)<br>
                            /// - On success, responds with [`DeleteBucketTaggingOutput`](crate::operation::delete_bucket_tagging::DeleteBucketTaggingOutput)
                            /// - On failure, responds with [`SdkError<DeleteBucketTaggingError>`](crate::operation::delete_bucket_tagging::DeleteBucketTaggingError)
    pub fn delete_bucket_tagging(&self) -> crate::operation::delete_bucket_tagging::builders::DeleteBucketTaggingFluentBuilder {
                                crate::operation::delete_bucket_tagging::builders::DeleteBucketTaggingFluentBuilder::new(self.handle.clone())
                            }
}

