// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`GetBucketConsistency`](crate::operation::get_bucket_consistency::builders::GetBucketConsistencyFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`bucket(impl Into<String>)`](crate::operation::get_bucket_consistency::builders::GetBucketConsistencyFluentBuilder::bucket) / [`set_bucket(Option<String>)`](crate::operation::get_bucket_consistency::builders::GetBucketConsistencyFluentBuilder::set_bucket):<br>required: **true**<br>(undocumented)<br>
                            /// - On success, responds with [`GetBucketConsistencyOutput`](crate::operation::get_bucket_consistency::GetBucketConsistencyOutput) with field(s):
    ///   - [`consistency(Option<String>)`](crate::operation::get_bucket_consistency::GetBucketConsistencyOutput::consistency): (undocumented)
    ///   - [`content_type(Option<String>)`](crate::operation::get_bucket_consistency::GetBucketConsistencyOutput::content_type): (undocumented)
                            /// - On failure, responds with [`SdkError<GetBucketConsistencyError>`](crate::operation::get_bucket_consistency::GetBucketConsistencyError)
    pub fn get_bucket_consistency(&self) -> crate::operation::get_bucket_consistency::builders::GetBucketConsistencyFluentBuilder {
                                crate::operation::get_bucket_consistency::builders::GetBucketConsistencyFluentBuilder::new(self.handle.clone())
                            }
}

