// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`GetBucketVersion2`](crate::operation::get_bucket_version2::builders::GetBucketVersion2FluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`bucket(impl Into<String>)`](crate::operation::get_bucket_version2::builders::GetBucketVersion2FluentBuilder::bucket) / [`set_bucket(Option<String>)`](crate::operation::get_bucket_version2::builders::GetBucketVersion2FluentBuilder::set_bucket):<br>required: **true**<br>(undocumented)<br>
    ///   - [`continuation_token(impl Into<String>)`](crate::operation::get_bucket_version2::builders::GetBucketVersion2FluentBuilder::continuation_token) / [`set_continuation_token(Option<String>)`](crate::operation::get_bucket_version2::builders::GetBucketVersion2FluentBuilder::set_continuation_token):<br>required: **false**<br>(undocumented)<br>
    ///   - [`delimiter(impl Into<String>)`](crate::operation::get_bucket_version2::builders::GetBucketVersion2FluentBuilder::delimiter) / [`set_delimiter(Option<String>)`](crate::operation::get_bucket_version2::builders::GetBucketVersion2FluentBuilder::set_delimiter):<br>required: **false**<br>(undocumented)<br>
    ///   - [`encoding_type(impl Into<String>)`](crate::operation::get_bucket_version2::builders::GetBucketVersion2FluentBuilder::encoding_type) / [`set_encoding_type(Option<String>)`](crate::operation::get_bucket_version2::builders::GetBucketVersion2FluentBuilder::set_encoding_type):<br>required: **false**<br>(undocumented)<br>
    ///   - [`fetch_owner(impl Into<String>)`](crate::operation::get_bucket_version2::builders::GetBucketVersion2FluentBuilder::fetch_owner) / [`set_fetch_owner(Option<String>)`](crate::operation::get_bucket_version2::builders::GetBucketVersion2FluentBuilder::set_fetch_owner):<br>required: **false**<br>(undocumented)<br>
    ///   - [`list_type(impl Into<String>)`](crate::operation::get_bucket_version2::builders::GetBucketVersion2FluentBuilder::list_type) / [`set_list_type(Option<String>)`](crate::operation::get_bucket_version2::builders::GetBucketVersion2FluentBuilder::set_list_type):<br>required: **true**<br>(undocumented)<br>
    ///   - [`marker(impl Into<String>)`](crate::operation::get_bucket_version2::builders::GetBucketVersion2FluentBuilder::marker) / [`set_marker(Option<String>)`](crate::operation::get_bucket_version2::builders::GetBucketVersion2FluentBuilder::set_marker):<br>required: **false**<br>(undocumented)<br>
    ///   - [`max_keys(impl Into<String>)`](crate::operation::get_bucket_version2::builders::GetBucketVersion2FluentBuilder::max_keys) / [`set_max_keys(Option<String>)`](crate::operation::get_bucket_version2::builders::GetBucketVersion2FluentBuilder::set_max_keys):<br>required: **false**<br>(undocumented)<br>
    ///   - [`prefix(impl Into<String>)`](crate::operation::get_bucket_version2::builders::GetBucketVersion2FluentBuilder::prefix) / [`set_prefix(Option<String>)`](crate::operation::get_bucket_version2::builders::GetBucketVersion2FluentBuilder::set_prefix):<br>required: **false**<br>(undocumented)<br>
    ///   - [`start_after(impl Into<String>)`](crate::operation::get_bucket_version2::builders::GetBucketVersion2FluentBuilder::start_after) / [`set_start_after(Option<String>)`](crate::operation::get_bucket_version2::builders::GetBucketVersion2FluentBuilder::set_start_after):<br>required: **false**<br>(undocumented)<br>
                            /// - On success, responds with [`GetBucketVersion2Output`](crate::operation::get_bucket_version2::GetBucketVersion2Output) with field(s):
    ///   - [`common_prefixes(Option<String>)`](crate::operation::get_bucket_version2::GetBucketVersion2Output::common_prefixes): (undocumented)
    ///   - [`contents(Option<Vec::<Contents>>)`](crate::operation::get_bucket_version2::GetBucketVersion2Output::contents): (undocumented)
    ///   - [`content_type(Option<String>)`](crate::operation::get_bucket_version2::GetBucketVersion2Output::content_type): (undocumented)
    ///   - [`continuation_token(Option<String>)`](crate::operation::get_bucket_version2::GetBucketVersion2Output::continuation_token): (undocumented)
    ///   - [`delimiter(Option<String>)`](crate::operation::get_bucket_version2::GetBucketVersion2Output::delimiter): (undocumented)
    ///   - [`encoding_type(Option<String>)`](crate::operation::get_bucket_version2::GetBucketVersion2Output::encoding_type): (undocumented)
    ///   - [`is_truncated(Option<bool>)`](crate::operation::get_bucket_version2::GetBucketVersion2Output::is_truncated): (undocumented)
    ///   - [`key_count(Option<String>)`](crate::operation::get_bucket_version2::GetBucketVersion2Output::key_count): (undocumented)
    ///   - [`max_keys(Option<String>)`](crate::operation::get_bucket_version2::GetBucketVersion2Output::max_keys): (undocumented)
    ///   - [`name(Option<String>)`](crate::operation::get_bucket_version2::GetBucketVersion2Output::name): (undocumented)
    ///   - [`next_continuation_token(Option<String>)`](crate::operation::get_bucket_version2::GetBucketVersion2Output::next_continuation_token): (undocumented)
    ///   - [`prefix(Option<String>)`](crate::operation::get_bucket_version2::GetBucketVersion2Output::prefix): (undocumented)
    ///   - [`start_after(Option<String>)`](crate::operation::get_bucket_version2::GetBucketVersion2Output::start_after): (undocumented)
                            /// - On failure, responds with [`SdkError<GetBucketVersion2Error>`](crate::operation::get_bucket_version2::GetBucketVersion2Error)
    pub fn get_bucket_version2(&self) -> crate::operation::get_bucket_version2::builders::GetBucketVersion2FluentBuilder {
                                crate::operation::get_bucket_version2::builders::GetBucketVersion2FluentBuilder::new(self.handle.clone())
                            }
}

