// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`GetBucketObjectVersions`](crate::operation::get_bucket_object_versions::builders::GetBucketObjectVersionsFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`bucket(impl Into<String>)`](crate::operation::get_bucket_object_versions::builders::GetBucketObjectVersionsFluentBuilder::bucket) / [`set_bucket(Option<String>)`](crate::operation::get_bucket_object_versions::builders::GetBucketObjectVersionsFluentBuilder::set_bucket):<br>required: **true**<br>(undocumented)<br>
    ///   - [`delimiter(impl Into<String>)`](crate::operation::get_bucket_object_versions::builders::GetBucketObjectVersionsFluentBuilder::delimiter) / [`set_delimiter(Option<String>)`](crate::operation::get_bucket_object_versions::builders::GetBucketObjectVersionsFluentBuilder::set_delimiter):<br>required: **false**<br>(undocumented)<br>
    ///   - [`encoding_type(impl Into<String>)`](crate::operation::get_bucket_object_versions::builders::GetBucketObjectVersionsFluentBuilder::encoding_type) / [`set_encoding_type(Option<String>)`](crate::operation::get_bucket_object_versions::builders::GetBucketObjectVersionsFluentBuilder::set_encoding_type):<br>required: **false**<br>(undocumented)<br>
    ///   - [`key_marker(impl Into<String>)`](crate::operation::get_bucket_object_versions::builders::GetBucketObjectVersionsFluentBuilder::key_marker) / [`set_key_marker(Option<String>)`](crate::operation::get_bucket_object_versions::builders::GetBucketObjectVersionsFluentBuilder::set_key_marker):<br>required: **false**<br>(undocumented)<br>
    ///   - [`max_keys(impl Into<String>)`](crate::operation::get_bucket_object_versions::builders::GetBucketObjectVersionsFluentBuilder::max_keys) / [`set_max_keys(Option<String>)`](crate::operation::get_bucket_object_versions::builders::GetBucketObjectVersionsFluentBuilder::set_max_keys):<br>required: **false**<br>(undocumented)<br>
    ///   - [`prefix(impl Into<String>)`](crate::operation::get_bucket_object_versions::builders::GetBucketObjectVersionsFluentBuilder::prefix) / [`set_prefix(Option<String>)`](crate::operation::get_bucket_object_versions::builders::GetBucketObjectVersionsFluentBuilder::set_prefix):<br>required: **false**<br>(undocumented)<br>
    ///   - [`version_id_marker(impl Into<String>)`](crate::operation::get_bucket_object_versions::builders::GetBucketObjectVersionsFluentBuilder::version_id_marker) / [`set_version_id_marker(Option<String>)`](crate::operation::get_bucket_object_versions::builders::GetBucketObjectVersionsFluentBuilder::set_version_id_marker):<br>required: **false**<br>(undocumented)<br>
                            /// - On success, responds with [`GetBucketObjectVersionsOutput`](crate::operation::get_bucket_object_versions::GetBucketObjectVersionsOutput) with field(s):
    ///   - [`content_type(Option<String>)`](crate::operation::get_bucket_object_versions::GetBucketObjectVersionsOutput::content_type): (undocumented)
    ///   - [`is_truncated(Option<bool>)`](crate::operation::get_bucket_object_versions::GetBucketObjectVersionsOutput::is_truncated): (undocumented)
    ///   - [`key_marker(Option<String>)`](crate::operation::get_bucket_object_versions::GetBucketObjectVersionsOutput::key_marker): (undocumented)
    ///   - [`max_keys(Option<String>)`](crate::operation::get_bucket_object_versions::GetBucketObjectVersionsOutput::max_keys): (undocumented)
    ///   - [`name(Option<String>)`](crate::operation::get_bucket_object_versions::GetBucketObjectVersionsOutput::name): (undocumented)
    ///   - [`prefix(Option<String>)`](crate::operation::get_bucket_object_versions::GetBucketObjectVersionsOutput::prefix): (undocumented)
    ///   - [`version(Option<Vec::<Version>>)`](crate::operation::get_bucket_object_versions::GetBucketObjectVersionsOutput::version): (undocumented)
    ///   - [`version_id_marker(Option<String>)`](crate::operation::get_bucket_object_versions::GetBucketObjectVersionsOutput::version_id_marker): (undocumented)
                            /// - On failure, responds with [`SdkError<GetBucketObjectVersionsError>`](crate::operation::get_bucket_object_versions::GetBucketObjectVersionsError)
    pub fn get_bucket_object_versions(&self) -> crate::operation::get_bucket_object_versions::builders::GetBucketObjectVersionsFluentBuilder {
                                crate::operation::get_bucket_object_versions::builders::GetBucketObjectVersionsFluentBuilder::new(self.handle.clone())
                            }
}

