// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`ListMultipartUploads`](crate::operation::list_multipart_uploads::builders::ListMultipartUploadsFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`bucket(impl Into<String>)`](crate::operation::list_multipart_uploads::builders::ListMultipartUploadsFluentBuilder::bucket) / [`set_bucket(Option<String>)`](crate::operation::list_multipart_uploads::builders::ListMultipartUploadsFluentBuilder::set_bucket):<br>required: **true**<br>(undocumented)<br>
    ///   - [`encoding_type(impl Into<String>)`](crate::operation::list_multipart_uploads::builders::ListMultipartUploadsFluentBuilder::encoding_type) / [`set_encoding_type(Option<String>)`](crate::operation::list_multipart_uploads::builders::ListMultipartUploadsFluentBuilder::set_encoding_type):<br>required: **false**<br>(undocumented)<br>
    ///   - [`key_marker(impl Into<String>)`](crate::operation::list_multipart_uploads::builders::ListMultipartUploadsFluentBuilder::key_marker) / [`set_key_marker(Option<String>)`](crate::operation::list_multipart_uploads::builders::ListMultipartUploadsFluentBuilder::set_key_marker):<br>required: **false**<br>(undocumented)<br>
    ///   - [`max_uploads(i32)`](crate::operation::list_multipart_uploads::builders::ListMultipartUploadsFluentBuilder::max_uploads) / [`set_max_uploads(Option<i32>)`](crate::operation::list_multipart_uploads::builders::ListMultipartUploadsFluentBuilder::set_max_uploads):<br>required: **false**<br>(undocumented)<br>
    ///   - [`prefix(impl Into<String>)`](crate::operation::list_multipart_uploads::builders::ListMultipartUploadsFluentBuilder::prefix) / [`set_prefix(Option<String>)`](crate::operation::list_multipart_uploads::builders::ListMultipartUploadsFluentBuilder::set_prefix):<br>required: **false**<br>(undocumented)<br>
    ///   - [`upload_id_marker(impl Into<String>)`](crate::operation::list_multipart_uploads::builders::ListMultipartUploadsFluentBuilder::upload_id_marker) / [`set_upload_id_marker(Option<String>)`](crate::operation::list_multipart_uploads::builders::ListMultipartUploadsFluentBuilder::set_upload_id_marker):<br>required: **false**<br>(undocumented)<br>
                            /// - On success, responds with [`ListMultipartUploadsOutput`](crate::operation::list_multipart_uploads::ListMultipartUploadsOutput) with field(s):
    ///   - [`bucket(Option<String>)`](crate::operation::list_multipart_uploads::ListMultipartUploadsOutput::bucket): (undocumented)
    ///   - [`content_type(Option<String>)`](crate::operation::list_multipart_uploads::ListMultipartUploadsOutput::content_type): (undocumented)
    ///   - [`is_truncated(Option<bool>)`](crate::operation::list_multipart_uploads::ListMultipartUploadsOutput::is_truncated): (undocumented)
    ///   - [`key_marker(Option<String>)`](crate::operation::list_multipart_uploads::ListMultipartUploadsOutput::key_marker): (undocumented)
    ///   - [`max_uploads(Option<i32>)`](crate::operation::list_multipart_uploads::ListMultipartUploadsOutput::max_uploads): (undocumented)
    ///   - [`next_key_marker(Option<String>)`](crate::operation::list_multipart_uploads::ListMultipartUploadsOutput::next_key_marker): (undocumented)
    ///   - [`next_upload_id_marker(Option<String>)`](crate::operation::list_multipart_uploads::ListMultipartUploadsOutput::next_upload_id_marker): (undocumented)
    ///   - [`upload(Option<Vec::<Upload>>)`](crate::operation::list_multipart_uploads::ListMultipartUploadsOutput::upload): (undocumented)
    ///   - [`upload_id_marker(Option<String>)`](crate::operation::list_multipart_uploads::ListMultipartUploadsOutput::upload_id_marker): (undocumented)
                            /// - On failure, responds with [`SdkError<ListMultipartUploadsError>`](crate::operation::list_multipart_uploads::ListMultipartUploadsError)
    pub fn list_multipart_uploads(&self) -> crate::operation::list_multipart_uploads::builders::ListMultipartUploadsFluentBuilder {
                                crate::operation::list_multipart_uploads::builders::ListMultipartUploadsFluentBuilder::new(self.handle.clone())
                            }
}

