// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`PutBucket`](crate::operation::put_bucket::builders::PutBucketFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`bucket(impl Into<String>)`](crate::operation::put_bucket::builders::PutBucketFluentBuilder::bucket) / [`set_bucket(Option<String>)`](crate::operation::put_bucket::builders::PutBucketFluentBuilder::set_bucket):<br>required: **true**<br>(undocumented)<br>
                            /// - On success, responds with [`PutBucketOutput`](crate::operation::put_bucket::PutBucketOutput) with field(s):
    ///   - [`location(Option<String>)`](crate::operation::put_bucket::PutBucketOutput::location): (undocumented)
                            /// - On failure, responds with [`SdkError<PutBucketError>`](crate::operation::put_bucket::PutBucketError)
    pub fn put_bucket(&self) -> crate::operation::put_bucket::builders::PutBucketFluentBuilder {
                                crate::operation::put_bucket::builders::PutBucketFluentBuilder::new(self.handle.clone())
                            }
}

