// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`PutBucketConsistency`](crate::operation::put_bucket_consistency::builders::PutBucketConsistencyFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`bucket(impl Into<String>)`](crate::operation::put_bucket_consistency::builders::PutBucketConsistencyFluentBuilder::bucket) / [`set_bucket(Option<String>)`](crate::operation::put_bucket_consistency::builders::PutBucketConsistencyFluentBuilder::set_bucket):<br>required: **true**<br>(undocumented)<br>
    ///   - [`x_ntap_sg_consistency(XNtapSgConsistencyOfPutBucketConsistencyRequest)`](crate::operation::put_bucket_consistency::builders::PutBucketConsistencyFluentBuilder::x_ntap_sg_consistency) / [`set_x_ntap_sg_consistency(Option<XNtapSgConsistencyOfPutBucketConsistencyRequest>)`](crate::operation::put_bucket_consistency::builders::PutBucketConsistencyFluentBuilder::set_x_ntap_sg_consistency):<br>required: **true**<br>(undocumented)<br>
                            /// - On success, responds with [`PutBucketConsistencyOutput`](crate::operation::put_bucket_consistency::PutBucketConsistencyOutput) with field(s):
    ///   - [`comtent_type(Option<String>)`](crate::operation::put_bucket_consistency::PutBucketConsistencyOutput::comtent_type): (undocumented)
                            /// - On failure, responds with [`SdkError<PutBucketConsistencyError>`](crate::operation::put_bucket_consistency::PutBucketConsistencyError)
    pub fn put_bucket_consistency(&self) -> crate::operation::put_bucket_consistency::builders::PutBucketConsistencyFluentBuilder {
                                crate::operation::put_bucket_consistency::builders::PutBucketConsistencyFluentBuilder::new(self.handle.clone())
                            }
}

