// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct AbortMultipartUploadOutput  {
}
impl AbortMultipartUploadOutput {
    /// Creates a new builder-style object to manufacture [`AbortMultipartUploadOutput`](crate::operation::abort_multipart_upload::AbortMultipartUploadOutput).
    pub fn builder() -> crate::operation::abort_multipart_upload::builders::AbortMultipartUploadOutputBuilder {
        crate::operation::abort_multipart_upload::builders::AbortMultipartUploadOutputBuilder::default()
    }
}

/// A builder for [`AbortMultipartUploadOutput`](crate::operation::abort_multipart_upload::AbortMultipartUploadOutput).
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
pub struct AbortMultipartUploadOutputBuilder {
}
impl AbortMultipartUploadOutputBuilder {
    /// Consumes the builder and constructs a [`AbortMultipartUploadOutput`](crate::operation::abort_multipart_upload::AbortMultipartUploadOutput).
    pub fn build(self) -> crate::operation::abort_multipart_upload::AbortMultipartUploadOutput {
        crate::operation::abort_multipart_upload::AbortMultipartUploadOutput {
        }
    }
}

