// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct PutBucketVersioningInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub bucket: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub content_md5: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub versioning_configuration: ::std::option::Option<crate::types::RequestVersioningConfiguration>,
}
impl  PutBucketVersioningInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn bucket(&self) -> ::std::option::Option<& str> {
        self.bucket.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn content_md5(&self) -> ::std::option::Option<& str> {
        self.content_md5.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn versioning_configuration(&self) -> ::std::option::Option<& crate::types::RequestVersioningConfiguration> {
        self.versioning_configuration.as_ref()
    }
}
impl PutBucketVersioningInput {
    /// Creates a new builder-style object to manufacture [`PutBucketVersioningInput`](crate::operation::put_bucket_versioning::PutBucketVersioningInput).
    pub fn builder() -> crate::operation::put_bucket_versioning::builders::PutBucketVersioningInputBuilder {
        crate::operation::put_bucket_versioning::builders::PutBucketVersioningInputBuilder::default()
    }
}

/// A builder for [`PutBucketVersioningInput`](crate::operation::put_bucket_versioning::PutBucketVersioningInput).
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
pub struct PutBucketVersioningInputBuilder {
    pub(crate) bucket: ::std::option::Option<::std::string::String>,
    pub(crate) content_md5: ::std::option::Option<::std::string::String>,
    pub(crate) versioning_configuration: ::std::option::Option<crate::types::RequestVersioningConfiguration>,
}
impl PutBucketVersioningInputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn bucket(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.bucket = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_bucket(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.bucket = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_bucket(&self) -> &::std::option::Option<::std::string::String> {
        &self.bucket
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn content_md5(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.content_md5 = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_content_md5(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.content_md5 = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_content_md5(&self) -> &::std::option::Option<::std::string::String> {
        &self.content_md5
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn versioning_configuration(mut self, input: crate::types::RequestVersioningConfiguration) -> Self {
        self.versioning_configuration = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_versioning_configuration(mut self, input: ::std::option::Option<crate::types::RequestVersioningConfiguration>) -> Self {
        self.versioning_configuration = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_versioning_configuration(&self) -> &::std::option::Option<crate::types::RequestVersioningConfiguration> {
        &self.versioning_configuration
    }
    /// Consumes the builder and constructs a [`PutBucketVersioningInput`](crate::operation::put_bucket_versioning::PutBucketVersioningInput).
    pub fn build(self) -> ::std::result::Result<crate::operation::put_bucket_versioning::PutBucketVersioningInput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::operation::put_bucket_versioning::PutBucketVersioningInput {
                bucket: self.bucket
                ,
                content_md5: self.content_md5
                ,
                versioning_configuration: self.versioning_configuration
                ,
            }
        )
    }
}

