// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Types for the `AbortMultipartUpload` operation.
pub mod abort_multipart_upload;

/// Types for the `CompleteMultipartUpload` operation.
pub mod complete_multipart_upload;

/// Types for the `DeleteBucket` operation.
pub mod delete_bucket;

/// Types for the `DeleteBucketCors` operation.
pub mod delete_bucket_cors;

/// Types for the `DeleteBucketLifecycle` operation.
pub mod delete_bucket_lifecycle;

/// Types for the `DeleteBucketPolicy` operation.
pub mod delete_bucket_policy;

/// Types for the `DeleteBucketTagging` operation.
pub mod delete_bucket_tagging;

/// Types for the `DeleteMultipleObjects` operation.
pub mod delete_multiple_objects;

/// Types for the `DeleteObject` operation.
pub mod delete_object;

/// Types for the `DeleteObjectTagging` operation.
pub mod delete_object_tagging;

/// Types for the `GetBucket` operation.
pub mod get_bucket;

/// Types for the `GetBucketACL` operation.
pub mod get_bucket_acl;

/// Types for the `GetBucketConsistency` operation.
pub mod get_bucket_consistency;

/// Types for the `GetBucketCors` operation.
pub mod get_bucket_cors;

/// Types for the `GetBucketLifecycleConfiguration` operation.
pub mod get_bucket_lifecycle_configuration;

/// Types for the `GetBucketObjectVersions` operation.
pub mod get_bucket_object_versions;

/// Types for the `GetBucketPolicy` operation.
pub mod get_bucket_policy;

/// Types for the `GetBucketTagging` operation.
pub mod get_bucket_tagging;

/// Types for the `GetBucketVersion2` operation.
pub mod get_bucket_version2;

/// Types for the `GetBucketVersioning` operation.
pub mod get_bucket_versioning;

/// Types for the `GetObject` operation.
pub mod get_object;

/// Types for the `GetObjectACL` operation.
pub mod get_object_acl;

/// Types for the `GetObjectTagging` operation.
pub mod get_object_tagging;

/// Types for the `GetService` operation.
pub mod get_service;

/// Types for the `HeadBucket` operation.
pub mod head_bucket;

/// Types for the `HeadObject` operation.
pub mod head_object;

/// Types for the `InitiateMultipartUpload` operation.
pub mod initiate_multipart_upload;

/// Types for the `ListMultipartUploads` operation.
pub mod list_multipart_uploads;

/// Types for the `ListParts` operation.
pub mod list_parts;

/// Types for the `PutBucket` operation.
pub mod put_bucket;

/// Types for the `PutBucketConsistency` operation.
pub mod put_bucket_consistency;

/// Types for the `PutBucketCors` operation.
pub mod put_bucket_cors;

/// Types for the `PutBucketLifecycleConfiguration` operation.
pub mod put_bucket_lifecycle_configuration;

/// Types for the `PutBucketPolicy` operation.
pub mod put_bucket_policy;

/// Types for the `PutBucketTagging` operation.
pub mod put_bucket_tagging;

/// Types for the `PutBucketVersioning` operation.
pub mod put_bucket_versioning;

/// Types for the `PutObject` operation.
pub mod put_object;

/// Types for the `PutObjectCopy` operation.
pub mod put_object_copy;

/// Types for the `PutObjectTagging` operation.
pub mod put_object_tagging;

/// Types for the `UploadPart` operation.
pub mod upload_part;

/// Types for the `UploadPartCopy` operation.
pub mod upload_part_copy;

