// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct GetBucketLifecycleConfigurationOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub rule: ::std::option::Option<crate::types::Rule>,
}
impl  GetBucketLifecycleConfigurationOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn rule(&self) -> ::std::option::Option<& crate::types::Rule> {
        self.rule.as_ref()
    }
}
impl GetBucketLifecycleConfigurationOutput {
    /// Creates a new builder-style object to manufacture [`GetBucketLifecycleConfigurationOutput`](crate::operation::get_bucket_lifecycle_configuration::GetBucketLifecycleConfigurationOutput).
    pub fn builder() -> crate::operation::get_bucket_lifecycle_configuration::builders::GetBucketLifecycleConfigurationOutputBuilder {
        crate::operation::get_bucket_lifecycle_configuration::builders::GetBucketLifecycleConfigurationOutputBuilder::default()
    }
}

/// A builder for [`GetBucketLifecycleConfigurationOutput`](crate::operation::get_bucket_lifecycle_configuration::GetBucketLifecycleConfigurationOutput).
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
pub struct GetBucketLifecycleConfigurationOutputBuilder {
    pub(crate) rule: ::std::option::Option<crate::types::Rule>,
}
impl GetBucketLifecycleConfigurationOutputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    pub fn rule(mut self, input: crate::types::Rule) -> Self {
        self.rule = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_rule(mut self, input: ::std::option::Option<crate::types::Rule>) -> Self {
        self.rule = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_rule(&self) -> &::std::option::Option<crate::types::Rule> {
        &self.rule
    }
    /// Consumes the builder and constructs a [`GetBucketLifecycleConfigurationOutput`](crate::operation::get_bucket_lifecycle_configuration::GetBucketLifecycleConfigurationOutput).
    pub fn build(self) -> crate::operation::get_bucket_lifecycle_configuration::GetBucketLifecycleConfigurationOutput {
        crate::operation::get_bucket_lifecycle_configuration::GetBucketLifecycleConfigurationOutput {
            rule: self.rule
            ,
        }
    }
}

